# **SpaceX  Falcon 9 first stage Landing Prediction**

In [19]:
import requests
import pandas as pd
import numpy as np
import datetime

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
# Takes the dataset and uses the rocket column to call the API and append the data to the list

def getBoosterVersion(data):
    for x in data['rocket']:
       if x:
        response = requests.get("https://api.spacexdata.com/v4/rockets/"+str(x)).json()
        BoosterVersion.append(response['name'])

From the <code>launchpad</code> we would like to know the name of the launch site being used, the longitude, and the latitude.

In [22]:
# Takes the dataset and uses the launchpad column to call the API and append the data to the list

def getLaunchSite(data):
    for x in data['launchpad']:
       if x:
         response = requests.get("https://api.spacexdata.com/v4/launchpads/"+str(x)).json()
         Longitude.append(response['longitude'])
         Latitude.append(response['latitude'])
         LaunchSite.append(response['name'])

From the <code>payload</code> we would like to learn the mass of the payload and the orbit that it is going to.

In [23]:
# Takes the dataset and uses the payloads column to call the API and append the data to the lists

def getPayloadData(data):
    for load in data['payloads']:
       if load:
        response = requests.get("https://api.spacexdata.com/v4/payloads/"+load).json()
        PayloadMass.append(response['mass_kg'])
        Orbit.append(response['orbit'])

From <code>cores</code> we would like to learn the outcome of the landing, the type of the landing, number of flights with that core, whether gridfins were used, whether the core is reused, whether legs were used, the landing pad used, the block of the core which is a number used to seperate version of cores, the number of times this specific core has been reused, and the serial of the core.

In [24]:
# Takes the dataset and uses the cores column to call the API and append the data to the lists

def getCoreData(data):
    for core in data['cores']:
            if core['core'] != None:
                response = requests.get("https://api.spacexdata.com/v4/cores/"+core['core']).json()
                Block.append(response['block'])
                ReusedCount.append(response['reuse_count'])
                Serial.append(response['serial'])
            else:
                Block.append(None)
                ReusedCount.append(None)
                Serial.append(None)
            Outcome.append(str(core['landing_success'])+' '+str(core['landing_type']))
            Flights.append(core['flight'])
            GridFins.append(core['gridfins'])
            Reused.append(core['reused'])
            Legs.append(core['legs'])
            LandingPad.append(core['landpad'])

Now let's start requesting rocket launch data from SpaceX API with the following URL:

In [25]:
spacex_url="https://api.spacexdata.com/v4/launches/past"

In [26]:
response = requests.get(spacex_url)

Check the content of the response

In [27]:
#print(response.content)

We see that the response contains massive information about SpaceX launches. Next, let's try to discover some more relevant information for this project.

### Requesting and parsing the SpaceX launch data using the GET request

To make the requested JSON results more consistent, we will use the following static response object for this project:

In [ ]:
static_json_url='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/API_call_spacex_api.json'

We should see that the request was successfull with the 200 status response code

In [ ]:
response.status_code

200

Now we decode the response content as a Json using <code>.json()</code> and turn it into a Pandas dataframe using <code>.json_normalize()</code>

In [ ]:
# Use json_normalize meethod to convert the json result into a dataframe

data = pd.json_normalize(response.json())

Using the dataframe <code>data</code> print the first 5 rows

In [ ]:
data.head()

,static_fire_date_utc,static_fire_date_unix,net,window,rocket,success,failures,details,crew,ships,capsules,payloads,launchpad,flight_number,name,date_utc,date_unix,date_local,date_precision,upcoming,cores,auto_update,tbd,launch_library_id,id,fairings.reused,fairings.recovery_attempt,fairings.recovered,fairings.ships,links.patch.small,links.patch.large,links.reddit.campaign,links.reddit.launch,links.reddit.media,links.reddit.recovery,links.flickr.small,links.flickr.original,links.presskit,links.webcast,links.youtube_id,links.article,links.wikipedia,fairings
0,2006-03-17T00:00:00.000Z,1.142554e+09,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 33, 'altitude': None, 'reason': 'merlin engine failure'}]",Engine failure at 33 seconds and loss of vehicle,[],[],[],[5eb0e4b5b6c3bb0006eeb1e1],5e9e4502f5090995de566f86,1,FalconSat,2006-03-24T22:30:00.000Z,1143239400,2006-03-25T10:30:00+12:00,hour,False,"[{'core': '5e9e289df35918033d3b2623', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",True,False,None,5eb87cd9ffd86e000604b32a,False,False,False,[],https://images2.imgbox.com/94/f2/NN6Ph45r_o.png,https://images2.imgbox.com/5b/02/QcxHUb5V_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=0a_00nJ_Y88,0a_00nJ_Y88,https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html,https://en.wikipedia.org/wiki/DemoSat,NaN
1,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 301, 'altitude': 289, 'reason': 'harmonic oscillation leading to premature engine shutdown'}]","Successful first stage burn and transition to second stage, maximum altitude 289 km, Premature engine shutdown at T+7 min 30 s, Failed to reach orbit, Failed to recover first stage",[],[],[],[5eb0e4b6b6c3bb0006eeb1e2],5e9e4502f5090995de566f86,2,DemoSat,2007-03-21T01:10:00.000Z,1174439400,2007-03-21T13:10:00+12:00,hour,False,"[{'core': '5e9e289ef35918416a3b2624', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",True,False,None,5eb87cdaffd86e000604b32b,False,False,False,[],https://images2.imgbox.com/f9/4a/ZboXReNb_o.png,https://images2.imgbox.com/80/a2/bkWotCIS_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=Lk4zQ2wP-Nc,Lk4zQ2wP-Nc,https://www.space.com/3590-spacex-falcon-1-rocket-fails-reach-orbit.html,https://en.wikipedia.org/wiki/DemoSat,NaN
2,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,False,"[{'time': 140, 'altitude': 35, 'reason': 'residual stage-1 thrust led to collision between stage 1 and stage 2'}]",Residual stage 1 thrust led to collision between stage 1 and stage 2,[],[],[],"[5eb0e4b6b6c3bb0006eeb1e3, 5eb0e4b6b6c3bb0006eeb1e4]",5e9e4502f5090995de566f86,3,Trailblazer,2008-08-03T03:34:00.000Z,1217734440,2008-08-03T15:34:00+12:00,hour,False,"[{'core': '5e9e289ef3591814873b2625', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",True,False,None,5eb87cdbffd86e000604b32c,False,False,False,[],https://images2.imgbox.com/6c/cb/na1tzhHs_o.png,https://images2.imgbox.com/4a/80/k1oAkY0k_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=v0w9p3U8860,v0w9p3U8860,http://www.spacex.com/news/2013/02/11/falcon-1-flight-3-mission-summary,https://en.wikipedia.org/wiki/Trailblazer_(satellite),NaN
3,2008-09-20T00:00:00.000Z,1.221869e+09,False,0.0,5e9d0d95eda69955f709d1eb,True,[],"Ratsat was carried to orbit on the first successful orbital launch of any privately funded and developed, liquid-propelled carrier rocket, the SpaceX Falcon 1",[],[],[],[5eb0e4b7b6c3bb0006eeb1e5],5e9e4502f5090995de566f86,4,RatSat,2008-09-28T23:15:00.000Z,1222643700,2008-09-28T11:15:00+12:00,hour,False,"[{'core': '5e9e289ef3591855dc3b2626', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",True,False,None,5eb87cdbffd86e000604b32d,False,False,False,[],https://images2.imgbox.com/95/39/sRqN7rsv_o.png,https://images2.imgbox.com/a3/99/qswRYzE8_o.png,None,None,None,None,[],[],None,https://www.youtube.com/watch?v=dLQ2tZEH6G0,dLQ2tZEH6G0,https://en.wikipedia.org/wiki/Ratsat,https://en.wikipedia.org/wiki/Ratsat,NaN
4,None,NaN,False,0.0,5e9d0d95eda69955f709d1eb,True,[],None,[],[],[],[5eb0e4b7b6c3bb0006eeb1e6],5e9e4502f5090995de566f86,5,RazakSat,2009-07-13T03:35:00.000Z,1247456100,2009-07-13T15:35:00+12:00,hour,False,"[{'core': '5e9e289ef359184f103b2627', 'flight': 1, 'gridfins': False, 'legs': False, 'reused': False, 'landing_attempt': False, 'landing_success': None, 'landing_type': None, 'landpad': None}]",True,False,None,5eb87cdcffd86e000604b32e,False,False,False,[],https://images2.imgbox.com/ab/5a/Pequxd5d_o.png,https://images2.imgbox.com/92/e4/7Cf6MLY0_o.png,None,None,None,None,[],[],http://www.spacex.com/press/2012/12/19/spacexs-falcon-1-successfully-delivers-razaksat-satellite-orbit,https://www.youtube.com/watch?v=yTaIDooc8Og,yTaIDooc8Og,http://www.spacex.com/news/2013/02/12/falcon-1-flight-5,https://en.wikipedia.org/wiki/RazakSAT,NaN

We notice that a lot of the data are IDs. For example the rocket column has no information about the rocket just an identification number.

We will now use the API again to get information about the launches using the IDs given for each launch. Specifically we will be using columns <code>rocket</code>, <code>payloads</code>, <code>launchpad</code>, and <code>cores</code>.

In [ ]:
# Lets take a subset of our dataframe keeping only the features we want and the flight number, and date_utc.
data = data[['rocket', 'payloads', 'launchpad', 'cores', 'flight_number', 'date_utc']]

# We will remove rows with multiple cores because those are falcon rockets with 2 extra rocket boosters and rows that have multiple payloads in a single rocket.
data = data[data['cores'].map(len)==1]
data = data[data['payloads'].map(len)==1]

# Since payloads and cores are lists of size 1 we will also extract the single value in the list and replace the feature.
data['cores'] = data['cores'].map(lambda x : x[0])
data['payloads'] = data['payloads'].map(lambda x : x[0])

# We also want to convert the date_utc to a datetime datatype and then extracting the date leaving the time
data['date'] = pd.to_datetime(data['date_utc']).dt.date

# Using the date we will restrict the dates of the launches
data = data[data['date'] <= datetime.date(2020, 11, 13)]

* From the <code>rocket</code> we would like to learn the booster name

* From the <code>payload</code> we would like to learn the mass of the payload and the orbit that it is going to

* From the <code>launchpad</code> we would like to know the name of the launch site being used, the longitude, and the latitude.

* From <code>cores</code> we would like to learn the outcome of the landing, the type of the landing, number of flights with that core, whether gridfins were used, whether the core is reused, whether legs were used, the landing pad used, the block of the core which is a number used to seperate version of cores, the number of times this specific core has been reused, and the serial of the core.

The data from these requests will be stored in lists and will be used to create a new dataframe.

In [ ]:
#Global variables

BoosterVersion = []
PayloadMass = []
Orbit = []
LaunchSite = []
Outcome = []
Flights = []
GridFins = []
Reused = []
Legs = []
LandingPad = []
Block = []
ReusedCount = []
Serial = []
Longitude = []
Latitude = []

These functions will apply the outputs globally to the above variables. Let's take a looks at <code>BoosterVersion</code> variable. Before we apply  <code>getBoosterVersion</code> the list is empty:

In [ ]:
BoosterVersion

[]

Now, let's apply <code> getBoosterVersion</code> function method to get the booster version

In [ ]:
# Call getBoosterVersion

getBoosterVersion(data)

the list has now been update

In [ ]:
BoosterVersion[0:5]

['Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 9']

we can apply the rest of the  functions here:

In [ ]:
# Call getLaunchSite

getLaunchSite(data)

In [ ]:
# Call getPayloadData

getPayloadData(data)

In [ ]:
# Call getCoreData

getCoreData(data)

Finally, let's construct our dataset using the data we have obtained. We combine the columns into a dictionary.

In [ ]:
launch_dict = {'FlightNumber': list(data['flight_number']),
'Date': list(data['date']),
'BoosterVersion':BoosterVersion,
'PayloadMass':PayloadMass,
'Orbit':Orbit,
'LaunchSite':LaunchSite,
'Outcome':Outcome,
'Flights':Flights,
'GridFins':GridFins,
'Reused':Reused,
'Legs':Legs,
'LandingPad':LandingPad,
'Block':Block,
'ReusedCount':ReusedCount,
'Serial':Serial,
'Longitude': Longitude,
'Latitude': Latitude}

In [ ]:
launch_dict

{'FlightNumber': [1,
  2,
  4,
  5,
  6,
  8,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  57,
  58,
  59,
  60,
  61,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  76,
  78,
  79,
  80,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  100,
  101,
  102,
  103,
  104,
  105,
  106],
 'Date': [datetime.date(2006, 3, 24),
  datetime.date(2007, 3, 21),
  datetime.date(2008, 9, 28),
  datetime.date(2009, 7, 13),
  datetime.date(2010, 6, 4),
  datetime.date(2012, 5, 22),
  datetime.date(2013, 3, 1),
  datetime.date(2013, 9, 29),
  datetime.date(2013, 12, 3),
  datetime.date(2014, 1, 6),
  datetime.date(2014, 4, 18),
  datetime.date(2014, 7, 14),
  datetime.date(2014, 8, 5),
  datetime.date(2014, 9, 7),
  datetime.date(2014, 9, 21),
  datetime.date(2015, 1, 10),
  datetime.date(2015, 2, 11),
  datetime.date(2015, 4, 14),
  datetime.date(2015, 4, 27),
  datetime.date(2015, 6, 28),
  datetime.date(2015, 12, 22),
  datetime.date(2016, 1, 17),
  datetime.date(2016, 3, 4),
  datetime.date(2016, 4, 8),
  datetime.date(2016, 5, 6),
  datetime.date(2016, 5, 27),
  datetime.date(2016, 7, 18),
  datetime.date(2016, 8, 14),
  datetime.date(2016, 9, 1),
  datetime.date(2017, 1, 14),
  datetime.date(2017, 2, 19),
  datetime.date(2017, 3, 16),
  datetime.date(2017, 3, 30),
  datetime.date(2017, 5, 1),
  datetime.date(2017, 5, 15),
  datetime.date(2017, 6, 3),
  datetime.date(2017, 6, 23),
  datetime.date(2017, 6, 25),
  datetime.date(2017, 7, 5),
  datetime.date(2017, 8, 14),
  datetime.date(2017, 8, 24),
  datetime.date(2017, 9, 7),
  datetime.date(2017, 10, 9),
  datetime.date(2017, 10, 11),
  datetime.date(2017, 10, 30),
  datetime.date(2017, 12, 15),
  datetime.date(2017, 12, 23),
  datetime.date(2018, 1, 8),
  datetime.date(2018, 1, 31),
  datetime.date(2018, 3, 6),
  datetime.date(2018, 3, 30),
  datetime.date(2018, 4, 2),
  datetime.date(2018, 4, 18),
  datetime.date(2018, 5, 11),
  datetime.date(2018, 6, 4),
  datetime.date(2018, 6, 29),
  datetime.date(2018, 7, 22),
  datetime.date(2018, 7, 25),
  datetime.date(2018, 8, 7),
  datetime.date(2018, 9, 10),
  datetime.date(2018, 10, 8),
  datetime.date(2018, 11, 15),
  datetime.date(2018, 12, 3),
  datetime.date(2018, 12, 5),
  datetime.date(2018, 12, 23),
  datetime.date(2019, 1, 11),
  datetime.date(2019, 3, 2),
  datetime.date(2019, 5, 4),
  datetime.date(2019, 5, 24),
  datetime.date(2019, 6, 12),
  datetime.date(2019, 7, 25),
  datetime.date(2019, 8, 6),
  datetime.date(2019, 11, 11),
  datetime.date(2019, 12, 5),
  datetime.date(2019, 12, 17),
  datetime.date(2020, 1, 7),
  datetime.date(2020, 1, 19),
  datetime.date(2020, 1, 29),
  datetime.date(2020, 2, 17),
  datetime.date(2020, 3, 7),
  datetime.date(2020, 3, 18),
  datetime.date(2020, 4, 22),
  datetime.date(2020, 5, 30),
  datetime.date(2020, 6, 4),
  datetime.date(2020, 6, 13),
  datetime.date(2020, 6, 30),
  datetime.date(2020, 7, 20),
  datetime.date(2020, 8, 18),
  datetime.date(2020, 8, 30),
  datetime.date(2020, 9, 3),
  datetime.date(2020, 10, 6),
  datetime.date(2020, 10, 18),
  datetime.date(2020, 10, 24),
  datetime.date(2020, 11, 5)],
 'BoosterVersion': ['Falcon 1',
  'Falcon 1',
  'Falcon 1',
  'Falcon 1',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9',
  'Falcon 9'],
 'PayloadMass': [20,
  None,
  165,
  200,
  None,
  525,
  677,
  500,
  3170,
  3325,
  2296,
  1316,
  4535,
  4428,
  2216,
  2395,
  570,
  1898,
  4707,
  2477,
  2034,
  553,
  5271,
  3136,
  4696,
  3100,
  2257,
  4600,
  5500,
  9600,
  2490,
  5600,
  5300,
  None,
  6070,
  2708,
  3669,
  9600,
  6761,
  2910,
  475,
  4990,
  9600,
  5200,
  3700,
  2205,
  9600,
  None,
  4230,
  6092,
  9600,
  2760,
  350,
  3750,
  5383.85,
  2410,
  7076,
  9600,
  5800,
  7060,
  2800,
  3000,
  4000,
  2573,
  4400,
  9600,
  12259,
  2482,
  13200,
  1425,
  2227.7,
  6500,
  15600,
  5000,
  6800,
  15600,
  None,
  15600,
  15600,
  1977,
  15600,
  15600,
  9525,
  15600,
  15600,
  3880,
  None,
  15600,
  1600,
  15600,
  15600,
  15600,
  15600,
  3681],
 'Orbit': ['LEO',
  'LEO',
  'LEO',
  'LEO',
  'LEO',
  'LEO',
  'ISS',
  'PO',
  'GTO',
  'GTO',
  'ISS',
  'LEO',
  'GTO',
  'GTO',
  'ISS',
  'ISS',
  'ES-L1',
  'ISS',
  'GTO',
  'ISS',
  'LEO',
  'PO',
  'GTO',
  'ISS',
  'GTO',
  'GTO',
  'ISS',
  'GTO',
  'GTO',
  'PO',
  'ISS',
  'GTO',
  'GTO',
  'LEO',
  'GTO',
  'ISS',
  'GTO',
  'PO',
  'GTO',
  'ISS',
  'SSO',
  'LEO',
  'PO',
  'GTO',
  'GTO',
  'ISS',
  'PO',
  'LEO',
  'GTO',
  'GTO',
  'PO',
  'ISS',
  'HEO',
  'GTO',
  'GTO',
  'ISS',
  'GTO',
  'PO',
  'GTO',
  'GTO',
  'SSO',
  'GTO',
  'SSO',
  'ISS',
  'MEO',
  'PO',
  'ISS',
  'ISS',
  'VLEO',
  'SSO',
  'ISS',
  'GTO',
  'VLEO',
  'ISS',
  'GTO',
  'VLEO',
  'SO',
  'VLEO',
  'VLEO',
  'ISS',
  'VLEO',
  'VLEO',
  'ISS',
  'VLEO',
  'VLEO',
  'MEO',
  'GEO',
  'VLEO',
  'SSO',
  'VLEO',
  'VLEO',
  'VLEO',
  'VLEO',
  'MEO'],
 'LaunchSite': ['Kwajalein Atoll',
  'Kwajalein Atoll',
  'Kwajalein Atoll',
  'Kwajalein Atoll',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'VAFB SLC 4E',
  'KSC LC 39A',
  'KSC LC 39A',
  'VAFB SLC 4E',
  'KSC LC 39A',
  'VAFB SLC 4E',
  'KSC LC 39A',
  'KSC LC 39A',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'KSC LC 39A',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'KSC LC 39A',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'KSC LC 39A',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'VAFB SLC 4E',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'KSC LC 39A',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'CCSFS SLC 40',
  'KSC LC 39A',
  'KSC LC 39A',
  'KSC LC 39A',
  'CCSFS SLC 40',
  'CCSFS SLC 40'],
 'Outcome': ['None None',
  'None None',
  'None None',
  'None None',
  'None None',
  'None None',
  'None None',
  'False Ocean',
  'None None',
  'None None',
  'True Ocean',
  'True Ocean',
  'None None',
  'None None',
  'False Ocean',
  'False ASDS',
  'True Ocean',
  'False ASDS',
  'None None',
  'None ASDS',
  'True RTLS',
  'False ASDS',
  'False ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True RTLS',
  'True ASDS',
  'None ASDS',
  'True ASDS',
  'True RTLS',
  'None None',
  'True ASDS',
  'True RTLS',
  'None None',
  'True RTLS',
  'True ASDS',
  'True ASDS',
  'None None',
  'True RTLS',
  'True ASDS',
  'True RTLS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True RTLS',
  'True Ocean',
  'True RTLS',
  'True Ocean',
  'None None',
  'None None',
  'None None',
  'True ASDS',
  'True ASDS',
  'None None',
  'None None',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True RTLS',
  'True ASDS',
  'True ASDS',
  'False RTLS',
  'None None',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True RTLS',
  'True RTLS',
  'None None',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'None None',
  'True ASDS',
  'False ASDS',
  'True RTLS',
  'False ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True RTLS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS',
  'True ASDS'],
 'Flights': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  2,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  1,
  2,
  2,
  1,
  2,
  1,
  2,
  2,
  1,
  1,
  2,
  2,
  1,
  1,
  2,
  1,
  2,
  2,
  3,
  1,
  1,
  2,
  1,
  1,
  3,
  2,
  2,
  3,
  4,
  1,
  3,
  4,
  4,
  3,
  4,
  2,
  5,
  4,
  1,
  5,
  3,
  1,
  2,
  6,
  4,
  2,
  3,
  6,
  3,
  1],
 'GridFins': [False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  False,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'Reused': [False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  True,
  False,
  False,
  False,
  True,
  False,
  False,
  False,
  False,
  False,
  False,
  True,
  False,
  True,
  True,
  False,
  True,
  False,
  True,
  True,
  False,
  False,
  True,
  True,
  False,
  False,
  True,
  False,
  True,
  True,
  True,
  False,
  False,
  True,
  False,
  False,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False],
 'Legs': [False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  False,
  True,
  True,
  False,
  False,
  False,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  False,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  False,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True,
  True],
 'LandingPad': [None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  None,
  '5e9e3032383ecb761634e7cb',
  None,
  '5e9e3032383ecb761634e7cb',
  None,
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb267a34e7c7',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb267a34e7c7',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb267a34e7c7',
  None,
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb267a34e7c7',
  None,
  '5e9e3032383ecb267a34e7c7',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  None,
  '5e9e3032383ecb267a34e7c7',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb267a34e7c7',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb267a34e7c7',
  None,
  '5e9e3032383ecb267a34e7c7',
  None,
  None,
  None,
  None,
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  None,
  None,
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb554034e7c9',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb267a34e7c7',
  None,
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb554034e7c9',
  '5e9e3032383ecb267a34e7c7',
  None,
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  None,
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb267a34e7c7',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb267a34e7c7',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3032383ecb6bb234e7ca',
  '5e9e3033383ecbb9e534e7cc',
  '5e9e3032383ecb6bb234e7ca'],
 'Block': [None,
  None,
  None,
  None,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  4,
  3,
  4,
  4,
  3,
  4,
  3,
  3,
  4,
  3,
  4,
  4,
  4,
  4,
  5,
  4,
  4,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5],
 'ReusedCount': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  3,
  1,
  1,
  2,
  4,
  3,
  9,
  4,
  2,
  3,
  0,
  0,
  9,
  12,
  3,
  9,
  12,
  3,
  2,
  4,
  5,
  3,
  9,
  3,
  12,
  3,
  5,
  4,
  12,
  13,
  9,
  5,
  12,
  13,
  9,
  5,
  12,
  13,
  12,
  12,
  8],
 'Serial': ['Merlin1A',
  'Merlin2A',
  'Merlin2C',
  'Merlin3C',
  'B0003',
  'B0005',
  'B0007',
  'B1003',
  'B1004',
  'B1005',
  'B1006',
  'B1007',
  'B1008',
  'B1011',
  'B1010',
  'B1012',
  'B1013',
  'B1015',
  'B1016',
  'B1018',
  'B1019',
  'B1017',
  'B1020',
  'B1021',
  'B1022',
  'B1023',
  'B1025',
  'B1026',
  'B1028',
  'B1029',
  'B1031',
  'B1030',
  'B1021',
  'B1032',
  'B1034',
  'B1035',
  'B1029',
  'B1036',
  'B1037',
  'B1039',
  'B1038',
  'B1040',
  'B1041',
  'B1031',
  'B1042',
  'B1035',
  'B1036',
  'B1043',
  'B1032',
  'B1044',
  'B1041',
  'B1039',
  'B1045',
  'B1046',
  'B1040',
  'B1045',
  'B1047',
  'B1048',
  'B1046',
  'B1049',
  'B1048',
  'B1047',
  'B1046',
  'B1050',
  'B1054',
  'B1049',
  'B1051',
  'B1056',
  'B1049',
  'B1051',
  'B1056',
  'B1047',
  'B1048',
  'B1059',
  'B1056',
  'B1049',
  'B1046',
  'B1051',
  'B1056',
  'B1059',
  'B1048',
  'B1051',
  'B1058',
  'B1049',
  'B1059',
  'B1060',
  'B1058',
  'B1049',
  'B1059',
  'B1060',
  'B1058',
  'B1051',
  'B1060',
  'B1062'],
 'Longitude': [167.7431292,
  167.7431292,
  167.7431292,
  167.7431292,
  -80.577366,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -120.610829,
  -80.6039558,
  -80.6039558,
  -120.610829,
  -80.6039558,
  -120.610829,
  -80.6039558,
  -80.6039558,
  -80.577366,
  -120.610829,
  -80.577366,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.577366,
  -80.577366,
  -80.6039558,
  -80.577366,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.6039558,
  -120.610829,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.6039558,
  -80.577366,
  -80.577366,
  -120.610829,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.6039558,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.577366,
  -80.6039558,
  -80.6039558,
  -80.6039558,
  -80.577366,
  -80.577366],
 'Latitude': [9.0477206,
  9.0477206,
  9.0477206,
  9.0477206,
  28.5618571,
  28.5618571,
  28.5618571,
  34.632093,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  34.632093,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  34.632093,
  28.6080585,
  28.6080585,
  28.6080585,
  28.6080585,
  28.6080585,
  28.6080585,
  28.6080585,
  34.632093,
  28.6080585,
  28.6080585,
  34.632093,
  28.6080585,
  34.632093,
  28.6080585,
  28.6080585,
  28.5618571,
  34.632093,
  28.5618571,
  28.5618571,
  28.5618571,
  34.632093,
  28.5618571,
  28.5618571,
  28.6080585,
  28.5618571,
  28.5618571,
  28.5618571,
  34.632093,
  28.5618571,
  28.5618571,
  34.632093,
  28.6080585,
  34.632093,
  28.5618571,
  28.5618571,
  34.632093,
  28.6080585,
  28.5618571,
  28.5618571,
  34.632093,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.6080585,
  28.5618571,
  28.5618571,
  28.5618571,
  28.6080585,
  28.6080585,
  28.6080585,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.5618571,
  28.6080585,
  28.6080585,
  28.6080585,
  28.5618571,
  28.5618571]}

Then, we need to create a Pandas data frame from the dictionary launch_dict.

Here, I wrote the following line to extract data from dictionary into a dataframe.

df = pd.DataFrame.from_dict(launch_dict)

After running this line, I encountered an error which said, "All arrays must be of same length".

This error was fixed after specifying parameter orient='index' as seen below.

In [ ]:
# Creating a dataframe from launch_dict

df = pd.DataFrame.from_dict(launch_dict, orient='index')

Show the summary of the dataframe

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93
FlightNumber,1,2,4,5,6,8,10,11,12,13,14,15,16,17,18,19,20,22,23,24,25,26,27,28,29,30,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,57,58,59,60,61,63,64,65,66,67,68,69,70,71,72,73,74,76,78,79,80,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,100,101,102,103,104,105,106
Date,2006-03-24,2007-03-21,2008-09-28,2009-07-13,2010-06-04,2012-05-22,2013-03-01,2013-09-29,2013-12-03,2014-01-06,2014-04-18,2014-07-14,2014-08-05,2014-09-07,2014-09-21,2015-01-10,2015-02-11,2015-04-14,2015-04-27,2015-06-28,2015-12-22,2016-01-17,2016-03-04,2016-04-08,2016-05-06,2016-05-27,2016-07-18,2016-08-14,2016-09-01,2017-01-14,2017-02-19,2017-03-16,2017-03-30,2017-05-01,2017-05-15,2017-06-03,2017-06-23,2017-06-25,2017-07-05,2017-08-14,2017-08-24,2017-09-07,2017-10-09,2017-10-11,2017-10-30,2017-12-15,2017-12-23,2018-01-08,2018-01-31,2018-03-06,2018-03-30,2018-04-02,2018-04-18,2018-05-11,2018-06-04,2018-06-29,2018-07-22,2018-07-25,2018-08-07,2018-09-10,2018-10-08,2018-11-15,2018-12-03,2018-12-05,2018-12-23,2019-01-11,2019-03-02,2019-05-04,2019-05-24,2019-06-12,2019-07-25,2019-08-06,2019-11-11,2019-12-05,2019-12-17,2020-01-07,2020-01-19,2020-01-29,2020-02-17,2020-03-07,2020-03-18,2020-04-22,2020-05-30,2020-06-04,2020-06-13,2020-06-30,2020-07-20,2020-08-18,2020-08-30,2020-09-03,2020-10-06,2020-10-18,2020-10-24,2020-11-05
BoosterVersion,Falcon 1,Falcon 1,Falcon 1,Falcon 1,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9,Falcon 9
PayloadMass,20,None,165,200,None,525,677,500,3170,3325,2296,1316,4535,4428,2216,2395,570,1898,4707,2477,2034,553,5271,3136,4696,3100,2257,4600,5500,9600,2490,5600,5300,None,6070,2708,3669,9600,6761,2910,475,4990,9600,5200,3700,2205,9600,None,4230,6092,9600,2760,350,3750,5383.85,2410,7076,9600,5800,7060,2800,3000,4000,2573,4400,9600,12259,2482,13200,1425,2227.7,6500,15600,5000,6800,15600,None,15600,15600,1977,15600,15600,9525,15600,15600,3880,None,15600,1600,15600,15600,15600,15600,3681
Orbit,LEO,LEO,LEO,LEO,LEO,LEO,ISS,PO,GTO,GTO,ISS,LEO,GTO,GTO,ISS,ISS,ES-L1,ISS,GTO,ISS,LEO,PO,GTO,ISS,GTO,GTO,ISS,GTO,GTO,PO,ISS,GTO,GTO,LEO,GTO,ISS,GTO,PO,GTO,ISS,SSO,LEO,PO,GTO,GTO,ISS,PO,LEO,GTO,GTO,PO,ISS,HEO,GTO,GTO,ISS,GTO,PO,GTO,GTO,SSO,GTO,SSO,ISS,MEO,PO,ISS,ISS,VLEO,SSO,ISS,GTO,VLEO,ISS,GTO,VLEO,SO,VLEO,VLEO,ISS,VLEO,VLEO,ISS,VLEO,VLEO,MEO,GEO,VLEO,SSO,VLEO,VLEO,VLEO,VLEO,MEO

### Filtering the dataframe to only include `Falcon 9` launches

Finally we will remove the Falcon 1 launches keeping only the Falcon 9 launches. Filter the data dataframe using the <code>BoosterVersion</code> column to only keep the Falcon 9 launches. Save the filtered data to a new dataframe called <code>data_falcon9</code>.

In [ ]:
df.head()
df = df.transpose()

In [ ]:
df.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2006-03-24,Falcon 1,20,LEO,Kwajalein Atoll,None None,1,False,False,False,None,None,0,Merlin1A,167.743129,9.047721
1,2,2007-03-21,Falcon 1,None,LEO,Kwajalein Atoll,None None,1,False,False,False,None,None,0,Merlin2A,167.743129,9.047721
2,4,2008-09-28,Falcon 1,165,LEO,Kwajalein Atoll,None None,1,False,False,False,None,None,0,Merlin2C,167.743129,9.047721
3,5,2009-07-13,Falcon 1,200,LEO,Kwajalein Atoll,None None,1,False,False,False,None,None,0,Merlin3C,167.743129,9.047721
4,6,2010-06-04,Falcon 9,None,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0003,-80.577366,28.561857

In [ ]:
data_falcon9 = df[df['BoosterVersion'] != 'Falcon 1']

In [ ]:
data_falcon9

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
4,6,2010-06-04,Falcon 9,None,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0003,-80.577366,28.561857
5,8,2012-05-22,Falcon 9,525,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0005,-80.577366,28.561857
6,10,2013-03-01,Falcon 9,677,ISS,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0007,-80.577366,28.561857
7,11,2013-09-29,Falcon 9,500,PO,VAFB SLC 4E,False Ocean,1,False,False,False,None,1,0,B1003,-120.610829,34.632093
8,12,2013-12-03,Falcon 9,3170,GTO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B1004,-80.577366,28.561857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,102,2020-09-03,Falcon 9,15600,VLEO,KSC LC 39A,True ASDS,2,True,True,True,5e9e3032383ecb6bb234e7ca,5,12,B1060,-80.603956,28.608058
90,103,2020-10-06,Falcon 9,15600,VLEO,KSC LC 39A,True ASDS,3,True,True,True,5e9e3032383ecb6bb234e7ca,5,13,B1058,-80.603956,28.608058
91,104,2020-10-18,Falcon 9,15600,VLEO,KSC LC 39A,True ASDS,6,True,True,True,5e9e3032383ecb6bb234e7ca,5,12,B1051,-80.603956,28.608058
92,105,2020-10-24,Falcon 9,15600,VLEO,CCSFS SLC 40,True ASDS,3,True,True,True,5e9e3033383ecbb9e534e7cc,5,12,B1060,-80.577366,28.561857
93,106,2020-11-05,Falcon 9,3681,MEO,CCSFS SLC 40,True ASDS,1,True,False,True,5e9e3032383ecb6bb234e7ca,5,8,B1062,-80.577366,28.561857

Now that we have removed some values we should reset the FlgihtNumber column

In [ ]:
data_falcon9.loc[:,'FlightNumber'] = list(range(1, data_falcon9.shape[0]+1))
data_falcon9

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
4,1,2010-06-04,Falcon 9,None,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0003,-80.577366,28.561857
5,2,2012-05-22,Falcon 9,525,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0005,-80.577366,28.561857
6,3,2013-03-01,Falcon 9,677,ISS,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0007,-80.577366,28.561857
7,4,2013-09-29,Falcon 9,500,PO,VAFB SLC 4E,False Ocean,1,False,False,False,None,1,0,B1003,-120.610829,34.632093
8,5,2013-12-03,Falcon 9,3170,GTO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B1004,-80.577366,28.561857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89,86,2020-09-03,Falcon 9,15600,VLEO,KSC LC 39A,True ASDS,2,True,True,True,5e9e3032383ecb6bb234e7ca,5,12,B1060,-80.603956,28.608058
90,87,2020-10-06,Falcon 9,15600,VLEO,KSC LC 39A,True ASDS,3,True,True,True,5e9e3032383ecb6bb234e7ca,5,13,B1058,-80.603956,28.608058
91,88,2020-10-18,Falcon 9,15600,VLEO,KSC LC 39A,True ASDS,6,True,True,True,5e9e3032383ecb6bb234e7ca,5,12,B1051,-80.603956,28.608058
92,89,2020-10-24,Falcon 9,15600,VLEO,CCSFS SLC 40,True ASDS,3,True,True,True,5e9e3033383ecbb9e534e7cc,5,12,B1060,-80.577366,28.561857
93,90,2020-11-05,Falcon 9,3681,MEO,CCSFS SLC 40,True ASDS,1,True,False,True,5e9e3032383ecb6bb234e7ca,5,8,B1062,-80.577366,28.561857

## Data Wrangling

We can see below that some of the rows are missing values in our dataset.

In [ ]:
data_falcon9.isnull().sum()

FlightNumber       0
Date               0
BoosterVersion     0
PayloadMass        5
Orbit              0
LaunchSite         0
Outcome            0
Flights            0
GridFins           0
Reused             0
Legs               0
LandingPad        26
Block              0
ReusedCount        0
Serial             0
Longitude          0
Latitude           0
dtype: int64

Before we can continue we must deal with these missing values. The <code>LandingPad</code> column will retain None values to represent when landing pads were not used.

### Dealing with Missing Values

Calculating below the mean for the <code>PayloadMass</code> using the <code>.mean()</code>. Then using the .mean() and the <code>.replace()</code> function to replace `np.nan` values in the data with the mean we calculated.

In [ ]:
data_falcon9.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
4,1,2010-06-04,Falcon 9,None,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0003,-80.577366,28.561857
5,2,2012-05-22,Falcon 9,525,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0005,-80.577366,28.561857
6,3,2013-03-01,Falcon 9,677,ISS,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0007,-80.577366,28.561857
7,4,2013-09-29,Falcon 9,500,PO,VAFB SLC 4E,False Ocean,1,False,False,False,None,1,0,B1003,-120.610829,34.632093
8,5,2013-12-03,Falcon 9,3170,GTO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B1004,-80.577366,28.561857

In [ ]:
# Calculate the mean value of PayloadMass column

mean1 = data_falcon9['PayloadMass'].mean()

# Replace the np.nan values with its mean value

data_falcon9['PayloadMass'].fillna(mean1, inplace=True)

data_falcon9.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
4,1,2010-06-04,Falcon 9,6123.547647,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0003,-80.577366,28.561857
5,2,2012-05-22,Falcon 9,525.000000,LEO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0005,-80.577366,28.561857
6,3,2013-03-01,Falcon 9,677.000000,ISS,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B0007,-80.577366,28.561857
7,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,None,1,0,B1003,-120.610829,34.632093
8,5,2013-12-03,Falcon 9,3170.000000,GTO,CCSFS SLC 40,None None,1,False,False,False,None,1,0,B1004,-80.577366,28.561857

We should see the number of missing values of the <code>PayLoadMass</code> change to zero.

Now, we should have no missing values in our dataset except for in <code>LandingPad</code>.